name: mml_comp_chem
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - anyio=4.10.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - async-timeout=5.0.1
  - attrs=25.3.0
  - autode=1.4.5
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.3
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.0
  - cpython=3.9.23
  - cuda-cudart=12.9.79
  - cuda-cudart_win-64=12.9.79
  - cuda-cupti=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - cycler=0.12.1
  - datamol=0.12.5
  - datasets=2.14.4
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - filelock=3.19.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freetype-py=2.3.0
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - graphite2=1.3.14
  - greenlet=3.2.4
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.0.0
  - hf-xet=1.1.8
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2024.2.1
  - ipykernel=6.30.1
  - ipython=8.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang13=21.1.7
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcudss=0.6.0.5
  - libcufft=11.4.1.4
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libdeflate=1.25
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmagma=2.9.0
  - libnvjitlink=12.9.86
  - libparquet=21.0.0
  - libpng=1.6.53
  - libpq=17.7
  - libprotobuf=6.31.1
  - librdkit=2025.03.5
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libtorch=2.7.1
  - libutf8proc=2.11.2
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - loguru=0.7.3
  - loky=3.5.5
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mkl=2024.2.2
  - mols2grid=2.0.0
  - mpmath=1.3.0
  - multidict=6.6.3
  - multiprocess=0.70.15
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - numpy=2.0.2
  - openjpeg=2.5.4
  - openssl=3.6.0
  - optree=0.17.0
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - py3dmol=2.5.2
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycairo=1.28.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.9.23
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch=2.7.1
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=27.0.2
  - qhull=2020.2
  - qt6-main=6.9.0
  - rdkit=2025.03.5
  - re2=2025.11.05
  - referencing=0.36.2
  - regex=2025.7.34
  - reportlab=4.4.1
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rlpycairo=0.2.0
  - rpds-py=0.27.0
  - safetensors=0.6.2
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - selfies=2.2.0
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlalchemy=2.0.43
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - sympy=1.14.0
  - tbb=2021.13.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.4
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.55.2
  - types-python-dateutil=2.9.0.20250809
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=3.5.2
  - win32_setctime=1.2.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
    - autogluon.common==1.4.0
    - autogluon.core==1.4.0
    - autogluon.features==1.4.0
    - autogluon.tabular==1.4.0
    - boto3==1.42.9
    - botocore==1.42.9
    - catboost==1.2.8
    - graphviz==0.21
    - jmespath==1.0.1
    - lightgbm==4.6.0
    - narwhals==2.13.0
    - plotly==6.5.0
    - pyarrow==20.0.0
    - s3transfer==0.16.0
    - urllib3==1.26.20
    - xgboost==2.1.4

